# Generated by Django 2.0 on 2017-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(help_text='Last day for pay')),
                ('recurring', models.BooleanField(default=False, help_text='Turn on to send a copy of the invoice again')),
                ('recurring_interval', models.IntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Bi-Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=3)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Overdue'), (2, 'Paid'), (3, 'Cancelled'), (4, 'Questioned'), (5, 'Draft')], default=0, help_text='Status of the invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
