# Generated by Django 2.0 on 2017-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='due_date',
            field=models.DateField(help_text='Last day for pay'),
        ),
    ]
